MODEL_PATH = "best.engine"

VALID_CLASSES = ["trash"]

CAMERA_HORIZONTAL_FOV = 70.42
CAMERA_VERTICAL_FOV = 43.3

FRAME_WIDTH = 640
FRAME_HEIGHT = 360

REAL_HEIGHT_CM = 12.0

CONFIDENCE_THRESHOLD = 0.5

DISTANCE_CALIBRATION_FACTOR = 0.8036